### ISSUE TITLE
Segfaults on surface

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#487]
I am experiencing segfaults on surface with LBANN built for Release mode, I played with LBANN built for Debug mode and get similar symptoms as below. I am using the latest code.
This happens especially when I am not using NCCL. It fails when starting up LBANN or initializing GPUs.
I ran LBANN without any option expecting it to show help and exit. Instead, it failed as below.
```
-----------------------------------------------------------------------------------------------------
(gdb) r 
Starting program: /p/lscratchh/.../lbann/build/gnu.Debug.surface.llnl.gov/lbann/build/model_zoo/lbann 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x2aaaf67cb700 (LWP 200879)]
[New Thread 0x2aaaf65ca700 (LWP 200878)]
In: PMI_Abort(2145039, Fatal error in PMPI_Init_thread:
Other MPI error, error stack:
MPIR_Init_thread(490)...........: 
MPID_Init(365)..................: 
MPIDI_Populate_vc_node_ids(1466): 
populate_ids_from_mapping(1190).: 
populate_ids_from_mapping(1101).: PMI_KVS_Commit returned -1
)
cudaFree error detected:

Asynchronous CUDA error (/p/lscratchh/.../lbann/build/gnu.Debug.surface.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:122): driver shutting down
std::terminate() will be called.
terminate called after throwing an instance of 'El::CudaError'
  what():  Asynchronous CUDA error (/p/lscratchh/.../lbann/build/gnu.Debug.surface.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:122): driver shutting down

Program received signal SIGABRT, Aborted.
0x00002aaaceebf495 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00002aaaceebf495 in raise () from /lib64/libc.so.6
#1  0x00002aaaceec0c75 in abort () from /lib64/libc.so.6
#2  0x00002aaace747d9d in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00002aaace745e26 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00002aaace745e71 in std::terminate ()
    at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00002aaaacf0b1ae in El::GPUManager::~GPUManager (this=0xc2d190, 
    __in_chrg=<optimized out>)
    at /p/lscratchh/.../lbann/build/gnu.Debug.surface.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:135
#6  0x00002aaaacf0d946 in std::default_delete<El::GPUManager>::operator() (
    this=0x2aaaadf037b0 <El::GPUManager::instance_>, __ptr=0xc2d190)
    at /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.9.3/include/c++/4.9.3/bits/unique_ptr.h:76
#7  0x00002aaaacf0d2eb in std::unique_ptr<El::GPUManager, std::default_delete<El::GPUManager> >::~unique_ptr (this=0x2aaaadf037b0 <El::GPUManager::instance_>, 
    __in_chrg=<optimized out>)
    at /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.9.3/include/c++/4.9.3/bits/unique_ptr.h:236
#8  0x00002aaaceec2d2d in __cxa_finalize () from /lib64/libc.so.6
#9  0x00002aaaabb043a3 in __do_global_dtors_aux ()
   from /p/lscratchh/.../lbann/build/gnu.Debug.surface.llnl.gov/lbann/build/liblbann.so
#10 0x00007fffffffb690 in ?? ()
#11 0x00002aaaaaab9fbc in _dl_fini () from /lib64/ld-linux-x86-64.so.2
Backtrace stopped: frame did not save the PC
-----------------------------------------------------------------------------------------------------
```
The LBANN built with Aluminum with NCCL backend rarely failed, but it did.
I think this is a pretty recent behavior. I did not see it during the most of the last week. It might have started around the weekend.

**Comment by JaeseungYeom** [comment]
That may be possible but the nodes that I get are more or less the same sets. However, this even happens with a single node.

**Comment by timmoon10** [comment]
I had some trouble with surface176 yesterday. I had similar troubles a few weeks ago and reported it to LC.

**Comment by JaeseungYeom** [comment]
The nodes just used for two failed jobs on surface are {167, 168,1 69, and 170} and {166, 167, 168, and 169}.

**Comment by JaeseungYeom** [comment]
For the record, the below is the error I got on ray using Naoya's MVAPICH2-GDR and Aluminum with NCCL backend. This does not happen often on ray.
```
WARNING: Could not achieve THREAD_MULTIPLE support.
code was compiled with LBANN_HAS_CUDNN, and we are using cudnn
[ray40:mpi_rank_7][error_sighandler] Caught error: Segmentation fault (signal 11)
[ray40:mpi_rank_4][error_sighandler] Caught error: Segmentation fault (signal 11)
[cli_5]: aborting job:
Fatal error in MPI_Testall:
Other MPI error, error stack:
MPI_Testall(253)..................: MPI_Testall(count=2, req_array=0x1100b8708804, flag=0x1100163f6280, status_array=0x1) failed
MPIDI_CH3I_Progress_test(573).....: 
handle_read(1371).................: 
handle_read_individual(1423)......: 
MPIDI_CH3I_MRAIL_Parse_header(419): Control shouldn't reach here in prototype, header %d
 (errno 120)

cudaFree error detected:

Asynchronous CUDA error (/p/gscratchr/...l/lbann/build/gnu.Release.ray.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:122): driver shutting down
std::terminate() will be called.
terminate called after throwing an instance of 'El::CudaError'
  what():  Asynchronous CUDA error (/p/gscratchr/.../lbann/build/gnu.Release.ray.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:122): driver shutting down
[ray40:mpi_rank_5][error_sighandler] Caught error: Aborted (signal 6)
[cli_13]: aborting job:
Fatal error in MPI_Testall:
Other MPI error, error stack:
MPI_Testall(253)..................: MPI_Testall(count=2, req_array=0x1100b8708584, flag=0x1100167f6280, status_array=0x1) failed
MPIDI_CH3I_Progress_test(573).....: 
handle_read(1371).................: 
handle_read_individual(1423)......: 
MPIDI_CH3I_MRAIL_Parse_header(419): Control shouldn't reach here in prototype, header %d
 (errno 116)

cudaFree error detected:

Asynchronous CUDA error (/p/gscratchr/.../lbann/build/gnu.Release.ray.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:122): driver shutting down
std::terminate() will be called.
terminate called after throwing an instance of 'El::CudaError'
  what():  Asynchronous CUDA error (/p/gscratchr/.../lbann/build/gnu.Release.ray.llnl.gov/hydrogen/src/src/core/imports/cuda.cpp:122): driver shutting down
[ray20:mpi_rank_13][error_sighandler] Caught error: Aborted (signal 6)
[ray40:mpispawn_1][readline] Unexpected End-Of-File on file descriptor 5. MPI process died?
[ray40:mpispawn_1][mtpmi_processops] Error while reading PMI socket. MPI process died?
[ray34:mpispawn_2][readline] Unexpected End-Of-File on file descriptor 7. MPI process died?
[ray34:mpispawn_2][mtpmi_processops] Error while reading PMI socket. MPI process died?
[ray40:mpispawn_1][child_handler] MPI process (rank: 4, pid: 65663) terminated with signal 11 -> abort job
[ray34:mpispawn_2][child_handler] MPI process (rank: 11, pid: 148512) terminated with signal 11 -> abort job
[ray20:mpispawn_3][readline] Unexpected End-Of-File on file descriptor 6. MPI process died?
[ray20:mpispawn_3][mtpmi_processops] Error while reading PMI socket. MPI process died?
[ray20:mpispawn_3][child_handler] MPI process (rank: 13, pid: 40276) terminated with signal 6 -> abort job
[ray53:mpirun_rsh][process_mpispawn_connection] mpispawn_1 from node ray34 aborted: Error while reading a PMI socket (4)
[ray53:mpispawn_0][read_size] Unexpected End-Of-File on file descriptor 11. MPI process died?
[ray53:mpispawn_0][read_size] Unexpected End-Of-File on file descriptor 11. MPI process died?
[ray53:mpispawn_0][handle_mt_peer] Error while reading PMI socket. MPI process died
```
