### ISSUE TITLE
lbann --version segfaults with CUDA 9 on Ubuntu 16.04

### ISSUE THREAD

**Issue by mxmlnkn** [LLNL/lbann#872]
My concrete build instructions can be seen in [this issue](https://github.com/LLNL/lbann/issues/855#issuecomment-462073056). When building from the CUDA 10 container with Ubuntu 18.04, then I can run `lbann --version` "successfully":

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    WARNING:

    You should always run with libnvidia-ml.so that is installed with your
    NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
    libnvidia-ml.so in GDK package is a stub library that is attached only for
    build purposes (e.g. machine that you build your application doesn't have
    to have Display Driver installed).
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    terminate called after throwing an instance of 'std::runtime_error'
      what():  NVML error

    Aborted

But when building from the CUDA 9 Ubuntu 16.04 base image, I get a segmentation fault on that same command even though everything compiles fine:

    #0  0x00007fffea516f59 in cudart::globalState::registerEntryFunction(void**, char const*, char*, char const*, int, uint3*, uint3*, dim3*, dim3*, int*) () from /opt/Aluminum/lib/libAl.so
    #1  0x00007fffea4f96bc in __cudaRegisterFunction () from /opt/Aluminum/lib/libAl.so
    #2  0x00007fffea54f398 in __nv_cudaEntityRegisterCallback(void**) () from /opt/Aluminum/lib/libAl.so
    #3  0x00007ffff76654b3 in __cudaRegisterLinkedBinary(__fatBinC_Wrapper_t const*, void (*)(void**), void*) ()
       from /opt/lbann/lib/liblbann.so
    #4  0x00007ffff766536a in __cudaRegisterLinkedBinary_68_tmpxft_000044c8_00000000_7_ztrmm_sm35_cpp2asm_asm_compute_37_cpp1_ii_2af62f32 ()
       from /opt/lbann/lib/liblbann.so
    #5  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffe108, env=env@entry=0x7fffffffe120)
        at dl-init.c:72
    #6  0x00007ffff7de77cb in call_init (env=0x7fffffffe120, argv=0x7fffffffe108, argc=2, l=<optimized out>) at dl-init.c:30
    #7  _dl_init (main_map=0x7ffff7ffe168, argc=2, argv=0x7fffffffe108, env=0x7fffffffe120) at dl-init.c:120
    #8  0x00007ffff7dd7c6a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
    #9  0x0000000000000002 in ?? ()
    #10 0x00007fffffffe427 in ?? ()
    #11 0x00007fffffffe43c in ?? ()
    #12 0x0000000000000000 in ?? ()

Possibly related: [1](https://stackoverflow.com/questions/35073759/why-do-i-get-a-segmentation-fault-when-calling-a-cuda-kernel-directly-from-a-sha?rq=1) [2](https://devtalk.nvidia.com/default/topic/917612/sigsev-at-start-of-cuda-program/) [3](https://stackoverflow.com/questions/37526858/cuda-rdc-thrust-in-multiple-shared-objects-results-in-sigsev-in-registerentr)

Like mentioned in the stackoverflow answer, I tried including `-DCMAKE_CUDA_FLAGS:STRING="--cudart shared"` for Aluminum, Elemental / Hydrogen, and LBANN but the problem won't go away.

**Comment by ndryden** [comment]
On the CUDA 10 issue, it appears like this might be some problem with the Nvidia Management Library.  Hydrogen makes use of this during startup to determine how many GPUs a node has.

I'm not sure what's going on with the CUDA 9 build.

**Comment by mxmlnkn** [comment]
The CUDA 10 is hopefully a non-issue. I think it only appears because I'm not running it on a GPU enabled host. The problem is that lcoally I only have a machine with drivers sufficient for CUDA 7 and the cluster only seem to have drivers sufficient for CUDA 9. So, It's nice and dandy that CUDA 10 builds and does not segfault but the CUDA 9 build is my final goal.

**Comment by ndryden** [comment]
Unfortunately, I'm not sure whether the issue is with LBANN or the CUDA runtime here. Can you try a debug build of LBANN and see whether that gets you more information? Or, have you tried building and running any of Nvidia's CUDA tests?
